import { Record } from "@/shared/models/activity/Record";
import { getRandomNumber } from "@/shared/utils/common/Random";

const RECORDS: Record[] = [
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'trying to overflow the comment zone to check it s display............................................................................' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'another testing of the comment zone for text-align' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aodnoanzd' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aojnojanonzocnoznconzeocnojzencinze' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apcpancnzpcnaonzcozocna' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apkncaozncpka,pc,apc,oka,' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aâpncnzconaojcojancpapcnpnazconzeoc' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'pacoazncipnepcnoenozeicbnzeic' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aopcnpazncoinzcojaojcbizebcizbeicn' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aincaonzcionazijcbiazbcizbci' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'trying to overflow the comment zone to check it s display............................................................................' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'another testing of the comment zone for text-align' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aodnoanzd' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aojnojanonzocnoznconzeocnojzencinze' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apcpancnzpcnaonzcozocna' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apkncaozncpka,pc,apc,oka,' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aâpncnzconaojcojancpapcnpnazconzeoc' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'pacoazncipnepcnoenozeicbnzeic' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aopcnpazncoinzcojaojcbizebcizbeicn' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aincaonzcionazijcbiazbcizbci' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'trying to overflow the comment zone to check it s display............................................................................' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'another testing of the comment zone for text-align' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aodnoanzd' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aojnojanonzocnoznconzeocnojzencinze' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apcpancnzpcnaonzcozocna' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apkncaozncpka,pc,apc,oka,' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aâpncnzconaojcojancpapcnpnazconzeoc' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'pacoazncipnepcnoenozeicbnzeic' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aopcnpazncoinzcojaojcbizebcizbeicn' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aincaonzcionazijcbiazbcizbci' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'trying to overflow the comment zone to check it s display............................................................................' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'another testing of the comment zone for text-align' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aodnoanzd' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aojnojanonzocnoznconzeocnojzencinze' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apcpancnzpcnaonzcozocna' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apkncaozncpka,pc,apc,oka,' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aâpncnzconaojcojancpapcnpnazconzeoc' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'pacoazncipnepcnoenozeicbnzeic' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aopcnpazncoinzcojaojcbizebcizbeicn' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aincaonzcionazijcbiazbcizbci' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'trying to overflow the comment zone to check it s display............................................................................' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'another testing of the comment zone for text-align' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aodnoanzd' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aojnojanonzocnoznconzeocnojzencinze' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apcpancnzpcnaonzcozocna' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'apkncaozncpka,pc,apc,oka,' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aâpncnzconaojcojancpapcnpnazconzeoc' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'pacoazncipnepcnoenozeicbnzeic' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aopcnpazncoinzcojaojcbizebcizbeicn' },
    { team_id: getRandomNumber(1, 4), team_num: getRandomNumber(1, 7), room_id: getRandomNumber(1, 13), slot_id: getRandomNumber(1, 18), points: getRandomNumber(0, 100), bonus: getRandomNumber(-50, 50), comment: 'aincaonzcionazijcbiazbcizbci' }
];

export async function getRecordsByActivityId(id: number): Promise<Record[]> {
    await fetch("https://data.bde-pps.fr/bde/images/logo/bde.svg");
    RECORDS.filter(value => value.team_id === id)
    return RECORDS;
}
